#!/bin/bash

# rsync --size-only --progress
# git pull

# are we in a normal BlobTracker repository
if [ -d .bt_objects -a -d .bt_layout ]; then
    true
# or a non-working directory BlobTracker repository
elif [ -d bt_objects -a -d bt_layout ]; then
    echo "You can't do a reset on non-working directory repositories."
    exit 1
else
    echo "This is not a BlobTracker repository."
    exit 1
fi

handle_dir() {
    for x in $1/*; do
        if [ $x == "$1/*" ]; then continue; fi
        if [ -d $x ]; then
            mkdir ../$x 2>/dev/null
            handle_dir $x
        else
            if [ $x -nt ../$x ]; then
                echo "updating  $x"
                SHA1=`cat $x`
                cp ../.bt_objects/$SHA1 ../$x
                DATE="`/bin/ls -lGg --full-time $x | cut -d " " -f 4-5`"
                touch -d "$DATE" ../$x
            fi
            if [ $x -ot ../$x ]; then
                echo "modified? $x"
            fi
        fi
    done
}

cd .bt_layout
handle_dir .

